[window]

opacity = 1
title = "For Zellij"

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

dimensions = { columns = 180, lines = 50 }


[font]

normal.family = "0xProto Nerd Font Mono"
bold.family = "0xProto Nerd Font Mono"
italic.family = "0xProto Nerd Font Mono"
bold_italic.family = "0xProto Nerd Font Mono"

size = 11.0

[keyboard]
bindings = [
{ key = "C", mods = "Alt", action = "Copy" },
{ key = "V", mods = "Alt", action = "Paste"}
]
