# https://taskfile.dev

version: '3'

vars:
  GREETING: "备份任务开始" 
  END: "备份任务结束" 

tasks:
  default:
      - echo "{{.GREETING}}"
      - task: password_store
      - task: dotconfig
      - task: info_backup
      - echo "{{.END}}"

  password_store:
    cmds:
      - echo start password backup...
      - cd ~/.password-store/;git fetch; git rebase master; git push origin master
      - echo "[+] backup done"
    silent: false

  info_backup:
    cmds:
      - echo start information backup
      - cd ~/Leyan/information/;git commit -a -m 'autocommit on change' ;git fetch; git rebase master; git push origin master
      - cd ~/Leyan/information/; git push origin master
      - echo "[+] information backup done"
    silent: false
    ignore_error: true

  dotconfig:
    cmds:
      - cp ~/.config/nvim/coc-settings.json ~/dotconfig/neovim/coc-settings.json 
      - cp ~/.config/nvim/init.vim ~/dotconfig/neovim/init.vim
      - cp ~/.tmux.conf ~/dotconfig/tmux/tmux.conf
      - cp ~/.spacemacs ~/dotconfig/spacemacs
      - cp ~/Taskfile.yml ~/dotconfig/task/Taskfile.yml
      - cd ~/dotconfig/; git commit -a -m 'autocommit on change'; git fetch; git rebase main; git push origin main; git push tee main
      - cd ~/dotconfig/;  git push origin main
      - echo "[+] dotconfig backup done"
    silent: false
    ignore_error: true

  wf:
    cmds:
      - cd ~/TemporalRelated/temporal;git pull origin main; gh issue list;gh pr list
      - echo ~/TemporalRelated/temporal
    silent: true

  wk:
    cmds:
      - cd ~/Github/weekly;git pull origin master; gh issue list; code .
    silent: true
